# -*- coding: utf-8 -*-
"""student-04-cd059360d159 (Mar 2, 2026, 11:42:51 AM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-04-994305c355a7/locations/us-central1/repositories/fba6f882-3364-44e1-aec9-3e0332cdc7c3
"""

# Install the requests library if you haven't already
!pip install requests==2.31.0

import requests
from typing import Optional, Dict

def get_nws_weather(latitude: float, longitude: float) -> Optional[Dict]:
    """
    Retrieves current weather forecast data from the National Weather Service (NWS) API
    for a given latitude and longitude.

    This function first queries the NWS /points endpoint to get the forecast office
    and grid coordinates, then uses that information to fetch the detailed forecast
    from the /gridpoints endpoint.

    Args:
        latitude: The geographical latitude (e.g., 39.7456).
        longitude: The geographical longitude (e.6., -97.6608).

    Returns:
        A dictionary containing the weather forecast data if successful,
        otherwise None.
    """
    base_url = "https://api.weather.gov"
    headers = {
        "User-Agent": "Google Colab NWS Weather App (student-04-cd059360d159@qwiklabs.net)",
        "Accept": "application/ld+json" # Or application/geo+json
    }

    # Step 1: Get forecast office and grid coordinates
    points_url = f"{base_url}/points/{latitude},{longitude}"
    try:
        points_response = requests.get(points_url, headers=headers)
        points_response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        points_data = points_response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching NWS points data: {e}")
        return None

    forecast_grid_data_url = points_data.get("properties", {}).get("forecastGridData")
    if not forecast_grid_data_url:
        print("Could not find forecast grid data URL.")
        return None

    # Step 2: Get detailed forecast using the grid data URL
    try:
        forecast_response = requests.get(forecast_grid_data_url, headers=headers)
        forecast_response.raise_for_status()
        forecast_data = forecast_response.json()
        return forecast_data
    except requests.exceptions.RequestException as e:
        print(f"Error fetching NWS forecast data: {e}")
        return None

import requests
import json

def geocode_place(place_name, api_key):
    """
    Converts a place name to its latitude and longitude coordinates using
    the Google Maps Geocoding API.

    Args:
        place_name (str): The name of the place to geocode (e.g., "Eiffel Tower").
        api_key (str): Your Google Cloud API key with Geocoding API enabled.

    Returns:
        dict or None: A dictionary containing 'lat' and 'lng' if successful,
                      otherwise None.
    """
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": place_name,
        "key": api_key
    }

    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()  # Raise an exception for HTTP errors (4xx or 5xx)
        data = response.json()

        if data["status"] == "OK" and data["results"]:
            location = data["results"][0]["geometry"]["location"]
            return {"lat": location["lat"], "lng": location["lng"]}
        else:
            print(f"Geocoding failed for '{place_name}': {data.get('status', 'Unknown error')}")
            return None
    except requests.exceptions.RequestException as e:
        print(f"An error occurred during the API request: {e}")
        return None
    except json.JSONDecodeError:
        print(f"Failed to decode JSON response from API.")
        return None

# Example Usage:
if __name__ == "__main__":
    # Replace 'YOUR_GOOGLE_CLOUD_API_KEY' with your actual API key
    # Ensure the Geocoding API is enabled in your Google Cloud project
    api_key = "MyAPIKey"

    place = "Googleplex, Mountain View, CA"
    coordinates = geocode_place(place, api_key)

    if coordinates:
        print(f"The coordinates for '{place}' are: Latitude {coordinates['lat']}, Longitude {coordinates['lng']}")

    place_fail = "NonExistentPlace123"
    coordinates_fail = geocode_place(place_fail, api_key)
    if coordinates_fail:
        print(f"The coordinates for '{place_fail}' are: Latitude {coordinates_fail['lat']}, Longitude {coordinates_fail['lng']}")

# Example usage:
# Replace "YOUR_GOOGLE_GEOCODING_API_KEY" with your actual API key
google_api_key = "AIzaSyCnScseVhdCkZUPwXbXmCfaOs-4hSq1k28"
address_to_geocode = "Eiffel Tower, Paris"

# tools.py (or integrated into your agent's code)

import requests
import json

def geocode_place(place_name: str, api_key: str = "AIzaSyCnScseVhdCkZUPwXbXmCfaOs-4hSq1k28") -> dict | None:
    """
    Converts a human-readable place name (e.g., "Eiffel Tower") into its
    latitude and longitude coordinates.

    Args:
        place_name (str): The name of the location to geocode.
        api_key (str): Your Google Cloud API key with Geocoding API enabled.
                       It's highly recommended to fetch this securely (e.g., from
                       environment variables or Secret Manager) in a real application.

    Returns:
        dict or None: A dictionary with 'latitude' and 'longitude' (e.g.,
                      {'latitude': 48.8584, 'longitude': 2.2945}) if successful,
                      otherwise None.
    """
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": place_name,
        "key": api_key # In a real app, this should be dynamically loaded securely
    }

    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()
        data = response.json()

        if data["status"] == "OK" and data["results"]:
            location = data["results"][0]["geometry"]["location"]
            return {"latitude": location["lat"], "longitude": location["lng"]}
        else:
            print(f"Geocoding failed for '{place_name}': {data.get('status', 'Unknown error')}")
            return None
    except requests.exceptions.RequestException as e:
        print(f"API request error: {e}")
        return None
    except json.JSONDecodeError:
        print(f"Failed to decode JSON from API response for '{place_name}'.")
        return None

# (Optional) Another example function
def calculate_distance(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """
    Calculates the distance between two points on Earth given their latitudes and longitudes
    using the Haversine formula. Returns the distance in kilometers.

    Args:
        lat1 (float): Latitude of the first point.
        lon1 (float): Longitude of the first point.
        lat2 (float): Latitude of the second point.
        lon2 (float): Longitude of the second point.

    Returns:
        float: The distance between the two points in kilometers.
    """
    import math

    R = 6371  # Radius of Earth in kilometers

    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad

    a = math.sin(dlat / 2)**2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    distance = R * c
    return distance

import vertexai
from vertexai.preview.generative_models import GenerativeModel, Tool, FunctionDeclaration

# Initialize Vertex AI (replace with your project and location)
vertexai.init(project="qwiklabs-gcp-04-994305c355a7", location="us-central1")

# --- Define the tool specifications ---
# These are declarative definitions for the LLM to understand what each tool does
# and what arguments it expects. The docstrings from your Python functions
# are crucial here.

geocode_tool_spec = FunctionDeclaration(
    name="geocode_place",
    description="Converts a human-readable place name (e.g., 'Eiffel Tower') into its "
                "latitude and longitude coordinates. This is useful for finding "
                "the geographic location of a given address or landmark.",
    parameters={
        "type": "object",
        "properties": {
            "place_name": {"type": "string", "description": "The name of the location to geocode."},
            # The API key would ideally be managed securely within the agent's environment
            # and not exposed directly to the LLM, or made an optional parameter if it can
            # be inferred. For simplicity here, we might pass it explicitly.
            # In a real ADK setup, you might omit this from the FunctionDeclaration
            # and inject it during the tool execution step.
            "api_key": {"type": "string", "description": "Your Google Cloud API key with Geocoding API enabled."}
        },
        "required": ["place_name"]
    },
)

calculate_distance_tool_spec = FunctionDeclaration(
    name="calculate_distance",
    description="Calculates the great-circle distance between two geographic points "
                "given their latitude and longitude coordinates. Returns the distance in kilometers.",
    parameters={
        "type": "object",
        "properties": {
            "lat1": {"type": "number", "description": "Latitude of the first point."},
            "lon1": {"type": "number", "description": "Longitude of the first point."},
            "lat2": {"type": "number", "description": "Latitude of the second point."},
            "lon2": {"type": "number", "description": "Longitude of the second point."}
        },
        "required": ["lat1", "lon1", "lat2", "lon2"]
    }
)

# Combine function declarations into a Tool object
my_tools = Tool(function_declarations=[geocode_tool_spec, calculate_distance_tool_spec])

# --- Create the GenerativeModel (Agent) ---
# Give the agent appropriate instructions (system instructions/persona).
# This guides the agent on when and how to use the tools.

agent_instructions = """
You are a helpful and knowledgeable geographic assistant.
Your primary goal is to provide accurate geographic information, including coordinates and distances.
- When asked to locate a place, use the `geocode_place` tool to find its latitude and longitude.
- When asked to calculate the distance between two specific points (given coordinates or places that need geocoding),
  first use `geocode_place` if needed, then use the `calculate_distance` tool.
- Always be precise and clearly state the information you found.
- If you cannot find a place, politely inform the user.
- Assume that "YOUR_GOOGLE_CLOUD_API_KEY" refers to the necessary API key for geocoding.
"""

# Instantiate the Generative Model with tools and instructions
model = GenerativeModel(
    "gemini-1.0-pro", # Or another suitable model
    tools=[my_tools],
    system_instruction=agent_instructions
)

# --- Define a tool resolver/executor ---
# This is a critical part where you map the LLM's requested function calls
# back to your actual Python functions.
def execute_tool_call(call):
    # In a real application, securely load your API key here
    GOOGLE_MAPS_API_KEY = "AIzaSyCnScseVhdCkZUPwXbXmCfaOs-4hSq1k28" # Replace with your actual key

    if call.function.name == "geocode_place":
        place_name = call.function.args["place_name"]
        # Pass the key to the geocode_place function
        return geocode_place(place_name, api_key=GOOGLE_MAPS_API_KEY)
    elif call.function.name == "calculate_distance":
        return calculate_distance(**call.function.args)
    else:
        raise ValueError(f"Unknown tool call: {call.function.name}")

# --- Interact with the Agent ---
chat = model.start_chat()

print("Agent: Hello! I can help you find locations and calculate distances. What can I do for you?")

while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Agent: Goodbye!")
        break

    response = chat.send_message(user_input)

    # Check if the model wants to call a tool
    if response.candidates[0].function_calls:
        for tool_call in response.candidates[0].function_calls:
            print(f"Agent wants to call tool: {tool_call.function.name} with args: {tool_call.function.args}")
            tool_result = execute_tool_call(tool_call)
            print(f"Tool execution result: {tool_result}")
            # Send the tool result back to the model for it to generate the final response
            response_after_tool = chat.send_message(
                tool_result,
                # Specifying the tool name for the context is important
                tool_name=tool_call.function.name
            )
            print(f"Agent: {response_after_tool.text}")
    else:
        # If no tool call, the model generates a direct text response
        print(f"Agent: {response.text}")

pip install litellm

# config.yaml (example for LiteLLM)
litellm_settings:
  model_list:
    - model_name: "gemini-pro-vision"
      litellm_params:
        model: "gemini/gemini-pro-vision"
    - model_name: "claude-3-opus"
      litellm_params:
        model: "anthropic/claude-3-opus-20240229"
        api_key: "os.environ/ANTHROPIC_API_KEY" # Load from env variable
    - model_name: "gpt-4o"
      litellm_params:
        model: "openai/gpt-4o"
        api_key: "os.environ/OPENAI_API_KEY" # Load from env variable

import vertexai
from vertexai.preview.generative_models import GenerativeModel, Tool, FunctionDeclaration

# For LiteLLM integration
from litellm import completion, model_list

# For direct Vertex AI models
from vertexai.generative_models import GenerativeModel as VertexGenerativeModel

# Initialize Vertex AI
vertexai.init(project="qwiklabs-gcp-04-994305c355a7", location="us-central1")

# --- Define a wrapper for multi-model access ---
class MultiModelAgent:
    def __init__(self, default_model_name: str, config_path: str = None):
        self.default_model_name = default_model_name
        # If using LiteLLM, load configuration
        if config_path:
            # LiteLLM allows dynamic loading of models/configs
            pass # Configuration is typically handled by LiteLLM env vars or its own config system

    def get_model(self, model_name: str = None):
        if not model_name:
            model_name = self.default_model_name

        if model_name.startswith("gemini/") or model_name.startswith("models/"):
            # Directly use Vertex AI SDK for Gemini models
            return VertexGenerativeModel(model_name.split('/')[-1]) # e.g., "gemini-pro"
        elif model_name in model_list: # Check if LiteLLM has it configured
             # This is a conceptual wrapper; actual LiteLLM integration might involve
             # directly calling litellm.completion with the model_name.
             # For agent's internal reasoning, you might just need a model client.
             print(f"Using LiteLLM for model: {model_name}")
             return lambda messages, tools=None, tool_config=None: \
                    completion(model=model_name, messages=messages, tools=tools, tool_choice=tool_config)
        else:
            raise ValueError(f"Unsupported or unconfigured model: {model_name}")

# --- Agent setup with dynamic model selection ---
# (Assuming geocode_place and calculate_distance tools are defined as before)

# Define tool specifications
# ... (geocode_tool_spec and calculate_distance_tool_spec from previous example)
# my_tools = Tool(function_declarations=[geocode_tool_spec, calculate_distance_tool_spec])

agent_instructions = """
You are an advanced geographic assistant. You have access to multiple large language models.
- For quick, factual lookups like geocoding, prefer the `gemini-pro` model.
- For complex reasoning or creative responses, you might consider `claude-3-opus` if available.
- Always use the `geocode_place` tool to find coordinates.
- Always use the `calculate_distance` tool for distance calculations.
- If a user asks for a very creative description of a location, mention you are switching to a more creative model.
"""

# Instantiate the MultiModelAgent helper
multi_model_agent_helper = MultiModelAgent(default_model_name="gemini-pro")

# The main generative model for the agent (this will still be a Vertex AI model)
# The multi-model selection happens *within* the agent's reasoning loop or tool execution.
# For simplicity, we'll start with Gemini-Pro as the core orchestrator.
orchestrator_model = GenerativeModel(
    "gemini-pro",
    tools=[my_tools],
    system_instruction=agent_instructions
)

# --- Define a tool resolver/executor with LLM calls ---
# This is where the agent can choose which LLM to use for internal thinking or specific tasks.
def execute_tool_call(call, model_chooser: MultiModelAgent):
    # ... (previous geocode_place and calculate_distance execution logic) ...

    # Example: if the agent itself needs to do some internal LLM call
    # and decides to use a specific model based on context.
    if call.function.name == "internal_reasoning_task":
        # The LLM asked to use an internal reasoning tool
        # and might suggest a model for it.
        model_for_reasoning = call.function.args.get("model_to_use", "gemini-pro")
        model_client = model_chooser.get_model(model_for_reasoning)

        # Example of making an internal call to another LLM
        if isinstance(model_client, VertexGenerativeModel):
            response = model_client.generate_content("Analyze this complex problem: ...")
            return response.text
        else: # LiteLLM client
            response = model_client(messages=[{"role": "user", "content": "Analyze this complex problem: ..."}])
            return response.choices[0].message.content
    # ... (rest of your tool execution)
    # For geocode_place, you still execute the Python function.
    # The decision to use different models often comes from the main LLM's *system instruction*
    # or by wrapping the entire conversation in a model selection logic.

# --- Example of dynamic model use within a conversation ---
chat = orchestrator_model.start_chat()

print("Agent: Hello! I can use multiple models to help you.")

while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Agent: Goodbye!")
        break

    # This is a simplified loop. In a more advanced ADK setup,
    # the orchestration of which model responds might be handled
    # by an auto-routing mechanism or more complex agent logic.
    # Here, the 'orchestrator_model' (Gemini-Pro) makes the primary decisions.
    # Its instructions tell it to "prefer gemini-pro for facts" or
    # "consider claude-3-opus for creative responses."
    # The actual switching of the *generation model* for a direct response
    # requires more sophisticated ADK patterns, possibly involving sub-agents or
    # custom model routing.

    response = chat.send_message(user_input)

    if response.candidates[0].function_calls:
        for tool_call in response.candidates[0].function_calls:
            print(f"Agent wants to call tool: {tool_call.function.name} with args: {tool_call.function.args}")
            # Execute tools. Note: if tool_call.function.name was for an *internal LLM call*,
            # you'd use the model_chooser here.
            tool_result = execute_tool_call(tool_call, multi_model_agent_helper)
            print(f"Tool execution result: {tool_result}")
            response_after_tool = chat.send_message(
                tool_result,
                tool_name=tool_call.function.name
            )
            print(f"Agent: {response_after_tool.text}")
    else:
        # If the orchestrator_model itself needs to generate text, it uses its own LLM (gemini-pro here).
        # To dynamically switch the *response* LLM, you would need to:
        # 1. Have the orchestrator_model explicitly "recommend" another LLM for the final response.
        # 2. Implement logic outside this chat.send_message to instantiate and call that recommended LLM.
        # This often involves more advanced "agent team" or "routing" patterns within ADK.
        print(f"Agent (Gemini-Pro): {response.text}")
